name: build simple python project

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      buildPackage:
        type: boolean
        description: 'Build Package'     
        required: true
        default: false
      versionType:
        type: choice
        description: 'Version Type'
        required: true
        default: 'PATCH'
        options: |
          - 'PATCH'
          - 'MINOR'
          - 'MAJOR'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: simple_python_project
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f simple_python_project/requirements-dev.txt ]; then pip install -r simple_python_project/requirements-dev.txt; fi
        # if [ -f simple_python_project/requirements.txt ]; then pip install -r simple_python_project/requirements.txt; fi
    - name: Run pylint
      run: |
        pylint simple_python_project/simple_py_proj --fail-under=8
    - name: Run pytest
      run: |
        pytest simple_python_project --cov-report=html --cov-branch --cov=.
    - name: Check coverage
      run: |
        coverage report --fail-under=80 --omit="setup.py,*/__init__.py,*/tests/*"
    - name: Build package
      run: |
        cd simple_python_project
        python -m build --wheel
        env:
          pkg_name: $(echo ls dist/*.whl)
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: $pkg_name
        path: simple_python_project/dist/*.whl
