name: build simple python project

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      buildPackage:
        description: Build Package
        required: true
        default: false
        type: boolean
      versionType:
        description: 'Version Type'
        required: true
        default: 'PATCH'
        type: choice
        options:
        - 'PATCH'
        - 'MINOR'
        - 'MAJOR'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: simple_python_project
    
    - name: check vars
      run: |
        echo "buildPackage: "${{ github.event.inputs.buildPackage }}
        echo "versionType: "${{ github.event.inputs.versionType }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f simple_python_project/requirements-dev.txt ]; then pip install -r simple_python_project/requirements-dev.txt; fi
        # if [ -f simple_python_project/requirements.txt ]; then pip install -r simple_python_project/requirements.txt; fi

    - name: Run pylint
      run: |
        pylint simple_python_project/simple_py_proj --fail-under=8

    - name: Run pytest
      run: |
        pytest simple_python_project --cov-report=html --cov-branch --cov=.

    - name: Check coverage
      run: |
        coverage report --fail-under=80 --omit="setup.py,*/__init__.py,*/tests/*"

    - name: Build package
      buildPackage:
      # if: ${{ github.event.inputs.buildPackage == 'true' }}
      run: |
        cd simple_python_project
        python -m build --wheel
        cd dist
        pkg_name=$(ls *.whl)
        echo "pkg_name: "$pkg_name
        echo "pkg_name=$pkg_name" >> $GITHUB_ENV
  
    - name: Upload package
      # if: ${{ github.event.inputs.buildPackage == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.pkg_name }}
        path: simple_python_project/dist/*.whl
